import { DurableObject } from 'cloudflare:workers';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { SSETransport } from './sse-transport';
import { WebSocketTransport } from './websocket-transport';
import { Implementation } from '@modelcontextprotocol/sdk/types.js';
import { IMcpServer } from './mcp-server-interface';
// Transport factory removed - using direct imports
const MAXIMUM_MESSAGE_SIZE = 4 * 1024 * 1024; // 4MB
export const SSE_MESSAGE_ENDPOINT = '/sse/message';
export const WEBSOCKET_ENDPOINT = '/ws';
export const MCP_SUBPROTOCOL = 'mcp';

/**
 * Interface for the WebSocket attachment data
 */
interface WebSocketAttachment {
	sessionId: string;
}

/**
 * McpDurableServer is a Durable Object implementation of an MCP server.
 * It supports SSE connections for event streaming and WebSocket connections with hibernation.
 */
export abstract class McpServerDO<Env = unknown> extends DurableObject<Env> {
	private server: IMcpServer;
	private sessions: Map<string, SSETransport | WebSocketTransport> = new Map();
	protected ctx: DurableObjectState; // Make ctx accessible to subclasses

	constructor(ctx: DurableObjectState, env: any, server?: IMcpServer) {
		super(ctx, env);
		this.ctx = ctx; // Store ctx for subclass access

		try {
			if (!server) {
				// Only call configureServer if we have a real McpServer instance (not a proxy)
				console.log(`[MCP Server] Initializing MCP server: ${this.getImplementation().name}`);
				const mcpServer = new McpServer(this.getImplementation());
				this.server = mcpServer;
				const configureResult = this.configureServer(mcpServer);
				if (configureResult instanceof Promise) {
					// If configureServer is async, we can't await it in constructor
					// Log a warning but continue - the server will be configured
					console.warn(`[MCP Server] configureServer returned a Promise - async configuration may not complete before first request`);
				}
				console.log(`[MCP Server] MCP server initialized: ${this.getImplementation().name}`);
			} else {
				this.server = server;
				console.log(`[MCP Server] Using provided server instance`);
			}
		} catch (error) {
			console.error(`[MCP Server] Error initializing MCP server:`, error);
			throw error;
		}
	}

	/**
	 * Returns the implementation information for the MCP server.
	 * Must be implemented by subclasses.
	 */
	abstract getImplementation(): Implementation;

	/**
	 * Abstract method that must be implemented by subclasses to configure the server instance.
	 * Called after server initialization to set up any additional server configuration, e.g., handlers of incoming RPC calls.
	 * Note: This is only called when using a real McpServer, not when using a proxy
	 * Can be synchronous or asynchronous (returning Promise<void>)
	 */
	abstract configureServer(server: McpServer): void | Promise<void>;

	protected processSSEConnection(request: Request): Response {
		// Session ID must exist as it will be created at the worker level prior to forwarding to DO.
		const url = new URL(request.url);
		const sessionId = url.searchParams.get('sessionId');
		if (!sessionId) {
			return new Response(`Missing sessionId parameter`, {
				status: 400,
			});
		}

		const { readable, writable } = new TransformStream();

		// Create message endpoint URL that preserves both proxyId and sessionId
		const messageEndpointUrl = new URL(SSE_MESSAGE_ENDPOINT, request.url);
		// Copy all search parameters from the original request to preserve proxyId
		url.searchParams.forEach((value, key) => {
			messageEndpointUrl.searchParams.set(key, value);
		});

		const transport = new SSETransport(writable.getWriter(), sessionId, messageEndpointUrl.toString());
		this.sessions.set(sessionId, transport);
		this.server.connect(transport);

		return new Response(readable, {
			headers: {
				'Content-Type': 'text/event-stream',
				'Cache-Control': 'no-cache, no-transform',
				Connection: 'keep-alive',
			},
		});
	}

	/**
	 * Process a WebSocket connection request
	 */
	protected processWebSocketConnection(request: Request): Response {
		// Verify the Upgrade header is present and is WebSocket
		const upgradeHeader = request.headers.get('Upgrade');
		if (!upgradeHeader || upgradeHeader.toLowerCase() !== 'websocket') {
			return new Response('Expected Upgrade: websocket', {
				status: 426,
			});
		}

		// Check for 'mcp' subprotocol
		const protocols = request.headers.get('Sec-WebSocket-Protocol');
		const acceptProtocol = protocols
			?.split(',')
			.map((p) => p.trim())
			.includes(MCP_SUBPROTOCOL);
		if (!acceptProtocol) {
			return new Response('Expected Sec-WebSocket-Protocol: mcp', {
				status: 426,
			});
		}

		// If no session was set, it will be automatically generated by the worker.
		const url = new URL(request.url);
		const sessionId = url.searchParams.get('sessionId');
		if (!sessionId) {
			return new Response(`Missing sessionId parameter`, {
				status: 400,
			});
		}

		// Create WebSocket pair
		const webSocketPair = new WebSocketPair();
		const [client, server] = Object.values(webSocketPair);

		// Store the sessionId as an attachment that will survive hibernation
		server.serializeAttachment({ sessionId });

		// Accept WebSocket with hibernation support
		this.ctx.acceptWebSocket(server);

		// Create transport and register handlers
		const transport = new WebSocketTransport(server, sessionId);
		this.sessions.set(sessionId, transport);
		this.server.connect(transport);

		// Return the client end of the WebSocket with the MCP subprotocol
		const headers = new Headers();
		headers.set('Sec-WebSocket-Protocol', MCP_SUBPROTOCOL);

		return new Response(null, {
			status: 101,
			webSocket: client,
			headers,
		});
	}

	/**
	 * Handle WebSocket messages
	 * This is called by the Durable Object runtime when a message is received
	 */
	async webSocketMessage(ws: WebSocket, data: string | ArrayBuffer): Promise<void> {
		// Find the transport associated with this WebSocket
		const transport = this.findWebSocketTransport(ws);
		if (transport) {
			transport.handleMessage(data);
		} else {
			console.error('[MCP] websocketSendMessage:No transport found for WebSocket');
		}
	}

	/**
	 * Handle WebSocket close events
	 */
	async webSocketClose(ws: WebSocket, code: number, reason: string, wasClean: boolean): Promise<void> {
		const transport = this.findWebSocketTransport(ws);
		if (transport) {
			this.sessions.delete(transport.sessionId);
			await transport.close(code, reason);
		}
	}

	/**
	 * Handle WebSocket errors
	 */
	async webSocketError(ws: WebSocket, error: unknown): Promise<void> {
		const transport = this.findWebSocketTransport(ws);
		if (transport) {
			transport.onerror?.(error instanceof Error ? error : new Error(String(error)));
		}
	}

	/**
	 * Find the WebSocketTransport associated with a specific WebSocket instance
	 */
	private findWebSocketTransport(ws: WebSocket): WebSocketTransport | null {
		// First try to get the sessionId from the attachment
		const attachment = ws.deserializeAttachment() as WebSocketAttachment | null;
		if (attachment?.sessionId) {
			const transport = this.sessions.get(attachment.sessionId);
			if (transport instanceof WebSocketTransport) {
				return transport;
			}
		}

		return null;
	}

	protected async processMcpRequest(request: Request): Promise<Response> {
		try {
			const contentType = request.headers.get('content-type') || '';
			if (!contentType.includes('application/json')) {
				console.warn(`[MCP Server] Unsupported content-type: ${contentType}`);
				return new Response(`Unsupported content-type: ${contentType}`, {
					status: 400,
				});
			}

			// Check if the request body is too large
			const contentLength = Number.parseInt(request.headers.get('content-length') || '0', 10);

			if (contentLength > MAXIMUM_MESSAGE_SIZE) {
				console.warn(`[MCP Server] Request body too large: ${contentLength} bytes`);
				return new Response(`Request body too large: ${contentLength} bytes`, {
					status: 400,
				});
			}

			const url = new URL(request.url);
			const sessionId = url.searchParams.get('sessionId');
			if (!sessionId) {
				console.warn(`[MCP Server] Missing sessionId parameter`);
				return new Response(`Missing sessionId parameter`, {
					status: 400,
				});
			}

			const transport = this.sessions.get(sessionId);
			if (!transport) {
				console.warn(`[MCP Server] Session not found: ${sessionId}. Active sessions: ${Array.from(this.sessions.keys()).join(', ')}`);
				return new Response(`Session not found`, {
					status: 404,
				});
			}

			// Only SSE transports handle POST messages since WebSocket messages are handled by the webSocketMessage method
			if (transport instanceof SSETransport) {
				console.log(`[MCP Server] Processing POST message for SSE session: ${sessionId}`);
				return await transport.handlePostMessage(request);
			} else {
				console.warn(`[MCP Server] Cannot send message to non-SSE transport for session: ${sessionId}`);
				return new Response(`Cannot send message to non-SSE transport`, {
					status: 400,
				});
			}
		} catch (error) {
			console.error(`[MCP Server] Error processing MCP request:`, error);
			return new Response(
				JSON.stringify({
					error: 'Internal server error',
					message: error instanceof Error ? error.message : String(error),
				}),
				{
					status: 500,
					headers: { 'Content-Type': 'application/json' },
				},
			);
		}
	}

	/**
	 * Main fetch handler
	 */
	async fetch(request: Request): Promise<Response> {
		try {
			const url = new URL(request.url);
			const path = url.pathname;

			console.log(`[MCP Server] fetch: ${request.method} ${path}`);

			// Process WebSocket upgrade requests
			if (path.endsWith(WEBSOCKET_ENDPOINT)) {
				return this.processWebSocketConnection(request);
			}

			// Process SSE connection requests
			if (path.endsWith('/sse')) {
				return this.processSSEConnection(request);
			}

			// Process SSE message requests
			if (path.endsWith(SSE_MESSAGE_ENDPOINT)) {
				return await this.processMcpRequest(request);
			}

			// Default response for unhandled paths
			console.warn(`[MCP Server] Unhandled path: ${path}`);
			return new Response('Not found', { status: 404 });
		} catch (error) {
			console.error(`[MCP Server] Error in fetch handler:`, error);
			return new Response(
				JSON.stringify({
					error: 'Internal server error',
					message: error instanceof Error ? error.message : String(error),
				}),
				{
					status: 500,
					headers: { 'Content-Type': 'application/json' },
				},
			);
		}
	}
}
